<?xml version="1.0" encoding="utf-8"?><Database Name="Taklito" Class="TaklitoLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Taklito.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="TaklitoData.Properties.Settings" SettingsPropertyName="TaklitoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Artist" Member="Artists">
    <Type Name="Artist">
      <Column Name="ArtistID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FK_GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_Artist" Member="Group" ThisKey="FK_GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Group_Artist" Member="Artists" ThisKey="GroupID" OtherKey="FK_GroupID" Type="Artist" />
    </Type>
  </Table>
</Database>